# dipdup: ignore
# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    owner: str
    spender: str


class Allowance(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: str


class TokenMetadata(BaseModel):
    class Config:
        extra = Extra.forbid

    token_id: str
    token_info: Dict[str, str]


class Balances(BaseModel):
    class Config:
        extra = Extra.forbid

    approvals: Dict[str, str]
    balance: str


class Fa12TokenStorage(BaseModel):
    class Config:
        extra = Extra.ignore

    # administrator: str
    # balances: Dict[str, Balances]
    # metadata: Dict[str, str]
    # token_metadata: Dict[str, TokenMetadata]
    # totalSupply: str
    # paused: bool
